@startuml
(浏览器) --> (请求域名解析)
(浏览器) --> (与web服务器建立tcp连接)
(浏览器) --> (渲染web服务器返回结果)
(DNS服务器)--> (接受浏览器解析请求)
(DNS服务器)--> (解析域名请求)
(DNS服务器)--> (返回解析结果给浏览器)
(web服务器)--> (接受浏览器请求)
(web服务器)--> (查找并解析资源)
(web服务器)--> (返回处理结果给浏览器)
@enduml